### ISSUE TITLE
如果不介意的话，希望给个模型下载链接，谢谢

### ISSUE THREAD

**Issue by zs901003** [Lily-Le/ebikedetection#1]
如果不介意的话，希望给个模型下载链接，谢谢

**Comment by Lily-Le** [comment]
抱歉，模型目前不作提供。可以基于yolo库加载预训练模型后在新的数据集上进行微调。

**Comment by zs901003** [comment]
请问数据集可以提供吗&nbsp; 或者出售吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chang ***@***.***&gt;; 
发送时间: 2024年4月15日(星期一) 中午1:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lily-Le/ebikedetection] 如果不介意的话，希望给个模型下载链接，谢谢 (Issue #1)














 
抱歉，模型目前不作提供。可以基于yolo库加载预训练模型后在新的数据集上进行微调。

**Comment by Lily-Le** [comment]
抱歉，目前数据集也不太方便出售或者公开....

**Comment by zs901003** [comment]
那您发这个意义何在啊

**Comment by Lily-Le** [comment]
数据集和模型暂时不作公开。可以自行寻找数据集训练。
